import {
  Controller,
  Get,
  Post,
  Put,
  Body,
  Param,
  Query,
  UseGuards,
  HttpStatus,
  HttpCode,
  Req,
} from '@nestjs/common';
import { Request } from 'express';
import {
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiBearerAuth,
  ApiParam,
  ApiQuery,
} from '@nestjs/swagger';
import { JwtAuthGuard } from '@common/guards/jwt-auth.guard';
import { RolesGuard } from '@common/guards/roles.guard';
import { Roles } from '@common/decorators/roles.decorator';
import { UserRole } from '@prisma/client';
import { ReaderBehaviorService } from '../services/reader-behavior.service';
import {
  CreateBehaviorFlagDto,
  InvestigateBehaviorFlagDto,
  TakeActionDto,
  GetBehaviorFlagsQueryDto,
  BehaviorFlagResponseDto,
  ReaderBehaviorReportDto,
  SuspiciousReaderDto,
  BehaviorFlagType,
  BehaviorFlagStatus,
} from '../dto/reader-behavior.dto';
import { IssueSeverity } from '../../reviews/dto/validate-review.dto';

@ApiTags('Admin - Reader Behavior')
@ApiBearerAuth()
@Controller('admin/reader-behavior')
@UseGuards(JwtAuthGuard, RolesGuard)
@Roles(UserRole.ADMIN)
export class ReaderBehaviorController {
  constructor(private readonly readerBehaviorService: ReaderBehaviorService) {}

  @Get('suspicious')
  @ApiOperation({ summary: 'Get list of suspicious readers' })
  @ApiResponse({
    status: HttpStatus.OK,
    description: 'List of suspicious readers',
    type: [SuspiciousReaderDto],
  })
  async getSuspiciousReaders(): Promise<SuspiciousReaderDto[]> {
    return this.readerBehaviorService.getSuspiciousReaders();
  }

  @Get('flags')
  @ApiOperation({ summary: 'Get behavior flags with optional filters' })
  @ApiQuery({ name: 'status', enum: BehaviorFlagStatus, required: false })
  @ApiQuery({ name: 'flagType', enum: BehaviorFlagType, required: false })
  @ApiQuery({ name: 'severity', enum: IssueSeverity, required: false })
  @ApiQuery({ name: 'readerProfileId', required: false })
  @ApiQuery({ name: 'isAutoGenerated', required: false, type: Boolean })
  @ApiResponse({
    status: HttpStatus.OK,
    description: 'List of behavior flags',
    type: [BehaviorFlagResponseDto],
  })
  async getBehaviorFlags(
    @Query() query: GetBehaviorFlagsQueryDto,
  ): Promise<BehaviorFlagResponseDto[]> {
    return this.readerBehaviorService.getBehaviorFlags(query);
  }

  @Get('stats')
  @ApiOperation({ summary: 'Get reader behavior statistics' })
  @ApiResponse({
    status: HttpStatus.OK,
    description: 'Behavior statistics',
  })
  async getBehaviorStats() {
    return this.readerBehaviorService.getBehaviorStats();
  }

  @Get('reader/:readerProfileId')
  @ApiOperation({ summary: 'Get behavior report for a specific reader' })
  @ApiParam({ name: 'readerProfileId', description: 'Reader profile ID' })
  @ApiResponse({
    status: HttpStatus.OK,
    description: 'Reader behavior report',
    type: ReaderBehaviorReportDto,
  })
  async getReaderBehaviorReport(
    @Param('readerProfileId') readerProfileId: string,
  ): Promise<ReaderBehaviorReportDto> {
    return this.readerBehaviorService.getReaderBehaviorReport(readerProfileId);
  }

  @Get('reader/:readerProfileId/analyze')
  @ApiOperation({ summary: 'Analyze reader behavior' })
  @ApiParam({ name: 'readerProfileId', description: 'Reader profile ID' })
  @ApiResponse({
    status: HttpStatus.OK,
    description: 'Reader behavior analysis',
    type: ReaderBehaviorReportDto,
  })
  async analyzeReaderBehavior(
    @Param('readerProfileId') readerProfileId: string,
  ): Promise<ReaderBehaviorReportDto> {
    return this.readerBehaviorService.analyzeReaderBehavior(readerProfileId);
  }

  @Post('flag')
  @ApiOperation({ summary: 'Flag a reader for suspicious behavior' })
  @ApiResponse({
    status: HttpStatus.CREATED,
    description: 'Behavior flag created',
    type: BehaviorFlagResponseDto,
  })
  async flagSuspiciousReader(
    @Body() dto: CreateBehaviorFlagDto,
    @Req() req: Request,
  ): Promise<BehaviorFlagResponseDto> {
    return this.readerBehaviorService.flagSuspiciousReader(dto, req.user!.id);
  }

  @Put('flags/:flagId/investigate')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Investigate a behavior flag' })
  @ApiParam({ name: 'flagId', description: 'Behavior flag ID' })
  @ApiResponse({
    status: HttpStatus.OK,
    description: 'Flag investigation updated',
    type: BehaviorFlagResponseDto,
  })
  async investigateBehaviorFlag(
    @Param('flagId') flagId: string,
    @Body() dto: InvestigateBehaviorFlagDto,
    @Req() req: Request,
  ): Promise<BehaviorFlagResponseDto> {
    return this.readerBehaviorService.investigateBehaviorFlag(flagId, dto, req.user!.id);
  }

  @Put('flags/:flagId/action')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Take action on a behavior flag' })
  @ApiParam({ name: 'flagId', description: 'Behavior flag ID' })
  @ApiResponse({
    status: HttpStatus.OK,
    description: 'Action taken on flag',
    type: BehaviorFlagResponseDto,
  })
  async takeAction(
    @Param('flagId') flagId: string,
    @Body() dto: TakeActionDto,
    @Req() req: Request,
  ): Promise<BehaviorFlagResponseDto> {
    return this.readerBehaviorService.takeAction(flagId, dto, req.user!.id);
  }
}
