import {
  IsString,
  IsEnum,
  IsOptional,
  IsNotEmpty,
  IsNumber,
  IsBoolean,
  MaxLength,
  MinLength,
  Min,
  Max,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { IssueSeverity } from '../../reviews/dto/validate-review.dto';

// Enums matching Prisma schema
export enum BehaviorFlagType {
  FAST_REVIEW = 'FAST_REVIEW',
  SIMILAR_TEXT = 'SIMILAR_TEXT',
  MULTIPLE_IP = 'MULTIPLE_IP',
  DEVICE_FINGERPRINT = 'DEVICE_FINGERPRINT',
  HIGH_REJECTION_RATE = 'HIGH_REJECTION_RATE',
  NEW_ACCOUNT_ABUSE = 'NEW_ACCOUNT_ABUSE',
}

export enum BehaviorFlagStatus {
  ACTIVE = 'ACTIVE',
  DISMISSED = 'DISMISSED',
  INVESTIGATED = 'INVESTIGATED',
  CONFIRMED = 'CONFIRMED',
}

export enum BehaviorAction {
  WARNED = 'WARNED',
  SUSPENDED = 'SUSPENDED',
  BANNED = 'BANNED',
  DISMISSED = 'DISMISSED',
}

// DTO for creating a behavior flag
export class CreateBehaviorFlagDto {
  @ApiProperty({
    description: 'Reader profile ID to flag',
    example: 'cly1abc123',
  })
  @IsString()
  @IsNotEmpty()
  readerProfileId: string;

  @ApiProperty({
    description: 'Type of suspicious behavior',
    enum: BehaviorFlagType,
    example: BehaviorFlagType.FAST_REVIEW,
  })
  @IsEnum(BehaviorFlagType)
  flagType: BehaviorFlagType;

  @ApiProperty({
    description: 'Detailed description of the suspicious behavior',
    example: 'Reader completed 5 reviews in less than 2 hours each',
  })
  @IsString()
  @IsNotEmpty()
  @MinLength(10)
  @MaxLength(2000)
  description: string;

  @ApiPropertyOptional({
    description: 'Severity of the flag',
    enum: IssueSeverity,
    example: IssueSeverity.HIGH,
  })
  @IsEnum(IssueSeverity)
  @IsOptional()
  severity?: IssueSeverity;

  @ApiPropertyOptional({
    description: 'JSON string with evidence data',
    example: '{"reviewIds": ["abc", "def"], "averageTime": 45}',
  })
  @IsString()
  @IsOptional()
  evidenceData?: string;

  @ApiPropertyOptional({
    description: 'Impact on reliability score (negative number)',
    example: -10,
  })
  @IsNumber()
  @IsOptional()
  @Type(() => Number)
  scoreImpact?: number;
}

// DTO for investigating a behavior flag
export class InvestigateBehaviorFlagDto {
  @ApiProperty({
    description: 'Notes from investigation',
    example: 'Confirmed suspicious pattern, reader IP matches 3 other accounts',
  })
  @IsString()
  @IsNotEmpty()
  @MinLength(10)
  @MaxLength(2000)
  investigationNotes: string;

  @ApiProperty({
    description: 'Status after investigation',
    enum: [BehaviorFlagStatus.INVESTIGATED, BehaviorFlagStatus.CONFIRMED, BehaviorFlagStatus.DISMISSED],
    example: BehaviorFlagStatus.CONFIRMED,
  })
  @IsEnum(BehaviorFlagStatus)
  status: BehaviorFlagStatus;
}

// DTO for taking action on a behavior flag
export class TakeActionDto {
  @ApiProperty({
    description: 'Action to take against the reader',
    enum: BehaviorAction,
    example: BehaviorAction.SUSPENDED,
  })
  @IsEnum(BehaviorAction)
  action: BehaviorAction;

  @ApiPropertyOptional({
    description: 'Notes about the action',
    example: 'Account suspended for 30 days due to suspected fraud',
  })
  @IsString()
  @IsOptional()
  @MaxLength(1000)
  notes?: string;
}

// DTO for filtering behavior flags
export class GetBehaviorFlagsQueryDto {
  @ApiPropertyOptional({
    description: 'Filter by status',
    enum: BehaviorFlagStatus,
  })
  @IsEnum(BehaviorFlagStatus)
  @IsOptional()
  status?: BehaviorFlagStatus;

  @ApiPropertyOptional({
    description: 'Filter by flag type',
    enum: BehaviorFlagType,
  })
  @IsEnum(BehaviorFlagType)
  @IsOptional()
  flagType?: BehaviorFlagType;

  @ApiPropertyOptional({
    description: 'Filter by severity',
    enum: IssueSeverity,
  })
  @IsEnum(IssueSeverity)
  @IsOptional()
  severity?: IssueSeverity;

  @ApiPropertyOptional({
    description: 'Filter by reader profile ID',
  })
  @IsString()
  @IsOptional()
  readerProfileId?: string;

  @ApiPropertyOptional({
    description: 'Filter by auto-generated flags only',
  })
  @IsBoolean()
  @IsOptional()
  @Type(() => Boolean)
  isAutoGenerated?: boolean;
}

// Response DTO for behavior flag
export class BehaviorFlagResponseDto {
  @ApiProperty()
  id: string;

  @ApiProperty()
  readerProfileId: string;

  @ApiProperty({ enum: BehaviorFlagType })
  flagType: BehaviorFlagType;

  @ApiProperty({ enum: IssueSeverity })
  severity: IssueSeverity;

  @ApiProperty()
  description: string;

  @ApiPropertyOptional()
  evidenceData?: string;

  @ApiProperty()
  scoreImpact: number;

  @ApiProperty({ enum: BehaviorFlagStatus })
  status: BehaviorFlagStatus;

  @ApiPropertyOptional()
  investigatedBy?: string;

  @ApiPropertyOptional()
  investigatedAt?: Date;

  @ApiPropertyOptional()
  investigationNotes?: string;

  @ApiPropertyOptional()
  actionTaken?: string;

  @ApiPropertyOptional()
  actionTakenAt?: Date;

  @ApiPropertyOptional()
  actionTakenBy?: string;

  @ApiProperty()
  isAutoGenerated: boolean;

  @ApiProperty()
  createdAt: Date;

  @ApiProperty()
  updatedAt: Date;
}

// Response DTO for reader behavior report
export class ReaderBehaviorReportDto {
  @ApiProperty()
  readerProfileId: string;

  @ApiProperty()
  readerName: string;

  @ApiProperty()
  readerEmail: string;

  @ApiProperty()
  reliabilityScore: number;

  @ApiProperty()
  completionRate: number;

  @ApiProperty()
  totalReviews: number;

  @ApiProperty()
  rejectedReviews: number;

  @ApiProperty()
  expiredAssignments: number;

  @ApiProperty()
  reviewsRemovedByAmazon: number;

  @ApiProperty()
  averageReviewTime: number; // in hours

  @ApiProperty()
  accountAge: number; // in days

  @ApiProperty()
  activeFlags: BehaviorFlagResponseDto[];

  @ApiProperty()
  flagCount: number;

  @ApiProperty()
  isFlagged: boolean;

  @ApiPropertyOptional()
  flagReason?: string;

  @ApiProperty()
  isActive: boolean;

  @ApiProperty()
  riskLevel: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
}

// DTO for suspicious readers list
export class SuspiciousReaderDto {
  @ApiProperty()
  readerProfileId: string;

  @ApiProperty()
  readerName: string;

  @ApiProperty()
  readerEmail: string;

  @ApiProperty()
  reliabilityScore: number;

  @ApiProperty()
  activeFlagCount: number;

  @ApiProperty()
  highestSeverity: IssueSeverity;

  @ApiProperty({ type: [String] })
  flagTypes: BehaviorFlagType[];

  @ApiProperty()
  lastFlagDate: Date;

  @ApiProperty()
  isFlagged: boolean;

  @ApiProperty()
  isActive: boolean;
}
