import { apiClient } from './client';

// ============================================
// TYPE DEFINITIONS (Match backend DTOs exactly)
// ============================================

export enum BehaviorFlagType {
  FAST_REVIEW = 'FAST_REVIEW',
  SIMILAR_TEXT = 'SIMILAR_TEXT',
  MULTIPLE_IP = 'MULTIPLE_IP',
  DEVICE_FINGERPRINT = 'DEVICE_FINGERPRINT',
  HIGH_REJECTION_RATE = 'HIGH_REJECTION_RATE',
  NEW_ACCOUNT_ABUSE = 'NEW_ACCOUNT_ABUSE',
}

export enum BehaviorFlagStatus {
  ACTIVE = 'ACTIVE',
  DISMISSED = 'DISMISSED',
  INVESTIGATED = 'INVESTIGATED',
  CONFIRMED = 'CONFIRMED',
}

export enum BehaviorAction {
  WARNED = 'WARNED',
  SUSPENDED = 'SUSPENDED',
  BANNED = 'BANNED',
  DISMISSED = 'DISMISSED',
}

export enum IssueSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export interface CreateBehaviorFlagDto {
  readerProfileId: string;
  flagType: BehaviorFlagType;
  description: string;
  severity?: IssueSeverity;
  evidenceData?: string;
  scoreImpact?: number;
}

export interface InvestigateBehaviorFlagDto {
  investigationNotes: string;
  status: BehaviorFlagStatus;
}

export interface TakeActionDto {
  action: BehaviorAction;
  notes?: string;
}

export interface BehaviorFlagResponse {
  id: string;
  readerProfileId: string;
  flagType: BehaviorFlagType;
  severity: IssueSeverity;
  description: string;
  evidenceData?: string;
  scoreImpact: number;
  status: BehaviorFlagStatus;
  investigatedBy?: string;
  investigatedAt?: string;
  investigationNotes?: string;
  actionTaken?: string;
  actionTakenAt?: string;
  actionTakenBy?: string;
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface ReaderBehaviorReport {
  readerProfileId: string;
  readerName: string;
  readerEmail: string;
  reliabilityScore: number;
  completionRate: number;
  totalReviews: number;
  rejectedReviews: number;
  expiredAssignments: number;
  reviewsRemovedByAmazon: number;
  averageReviewTime: number;
  accountAge: number;
  activeFlags: BehaviorFlagResponse[];
  flagCount: number;
  isFlagged: boolean;
  flagReason?: string;
  isActive: boolean;
  riskLevel: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
}

export interface SuspiciousReader {
  readerProfileId: string;
  readerName: string;
  readerEmail: string;
  reliabilityScore: number;
  activeFlagCount: number;
  highestSeverity: IssueSeverity;
  flagTypes: BehaviorFlagType[];
  lastFlagDate: string;
  isFlagged: boolean;
  isActive: boolean;
}

export interface BehaviorStats {
  totalFlags: number;
  activeFlags: number;
  suspiciousReaders: number;
  byFlagType: Record<string, number>;
  bySeverity: Record<string, number>;
  byAction: Record<string, number>;
}

export interface GetBehaviorFlagsQuery {
  status?: BehaviorFlagStatus;
  flagType?: BehaviorFlagType;
  severity?: IssueSeverity;
  readerProfileId?: string;
  isAutoGenerated?: boolean;
}

// ============================================
// API CLIENT METHODS
// ============================================

export const readerBehaviorApi = {
  /**
   * Get list of suspicious readers
   */
  async getSuspiciousReaders(): Promise<SuspiciousReader[]> {
    const response = await apiClient.get<SuspiciousReader[]>('/admin/reader-behavior/suspicious');
    return response.data;
  },

  /**
   * Get behavior flags with optional filters
   */
  async getBehaviorFlags(query?: GetBehaviorFlagsQuery): Promise<BehaviorFlagResponse[]> {
    const params = new URLSearchParams();
    if (query?.status) params.append('status', query.status);
    if (query?.flagType) params.append('flagType', query.flagType);
    if (query?.severity) params.append('severity', query.severity);
    if (query?.readerProfileId) params.append('readerProfileId', query.readerProfileId);
    if (query?.isAutoGenerated !== undefined)
      params.append('isAutoGenerated', String(query.isAutoGenerated));

    const response = await apiClient.get<BehaviorFlagResponse[]>(
      `/admin/reader-behavior/flags${params.toString() ? `?${params.toString()}` : ''}`,
    );
    return response.data;
  },

  /**
   * Get behavior statistics
   */
  async getBehaviorStats(): Promise<BehaviorStats> {
    const response = await apiClient.get<BehaviorStats>('/admin/reader-behavior/stats');
    return response.data;
  },

  /**
   * Get behavior report for a specific reader
   */
  async getReaderBehaviorReport(readerProfileId: string): Promise<ReaderBehaviorReport> {
    const response = await apiClient.get<ReaderBehaviorReport>(
      `/admin/reader-behavior/reader/${readerProfileId}`,
    );
    return response.data;
  },

  /**
   * Analyze reader behavior
   */
  async analyzeReaderBehavior(readerProfileId: string): Promise<ReaderBehaviorReport> {
    const response = await apiClient.get<ReaderBehaviorReport>(
      `/admin/reader-behavior/reader/${readerProfileId}/analyze`,
    );
    return response.data;
  },

  /**
   * Flag a reader for suspicious behavior
   */
  async flagSuspiciousReader(data: CreateBehaviorFlagDto): Promise<BehaviorFlagResponse> {
    const response = await apiClient.post<BehaviorFlagResponse>(
      '/admin/reader-behavior/flag',
      data,
    );
    return response.data;
  },

  /**
   * Investigate a behavior flag
   */
  async investigateBehaviorFlag(
    flagId: string,
    data: InvestigateBehaviorFlagDto,
  ): Promise<BehaviorFlagResponse> {
    const response = await apiClient.put<BehaviorFlagResponse>(
      `/admin/reader-behavior/flags/${flagId}/investigate`,
      data,
    );
    return response.data;
  },

  /**
   * Take action on a behavior flag
   */
  async takeAction(flagId: string, data: TakeActionDto): Promise<BehaviorFlagResponse> {
    const response = await apiClient.put<BehaviorFlagResponse>(
      `/admin/reader-behavior/flags/${flagId}/action`,
      data,
    );
    return response.data;
  },
};
